import { createRequire } from "node:module"
import { mkdir } from "node:fs/promises"
import { startPanelPreview } from "./composer-panel-preview.mjs"
const { chromium, expect } = createRequire(new URL("../../app/package.json", import.meta.url))("@playwright/test")
const preview = await startPanelPreview()
const fixture = preview.fixture
fixture.messages[1].info.tokens = { input: 200, output: 800, reasoning: 0, cache: { read: 0, write: 0 } }
const browser = await chromium.launch({ channel: "chrome", headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
await context.route("**/*", (route) =>
  new URL(route.request().url()).origin === preview.origin ? route.continue() : route.abort(),
)
const page = await context.newPage()
const errors = []
page.on("pageerror", (error) => errors.push(error.message))
const active = () => page.locator(".float-editor").or(page.locator(".prompt-box:not([inert])"))
const editor = () => active().getByRole("textbox", { name: "Message", exact: true })
const button = (name) => active().getByRole("button", { name, exact: true })
const inputs = () => fixture.calls.filter((call) => call.method === "POST" && call.path.endsWith("/input"))
const normal = () => fixture.calls.filter((call) => call.method === "POST" && call.path.endsWith("/prompt_async"))
const asides = () => fixture.calls.filter((call) => call.method === "POST" && call.path.endsWith("/aside"))
await mkdir("artifacts/direct-composer", { recursive: true })
try {
  await page.goto(preview.url, { waitUntil: "domcontentloaded" })
  await expect(button("Steer")).toHaveAttribute("data-keyboard-target", "true")
  await expect(button("Steer").locator("kbd")).toHaveText("⌘/Ctrl↵")
  await expect(button("Queue").locator("kbd")).toHaveText("⌘M →")
  await expect(active().locator(".direct-shortcuts")).toHaveCount(0)
  await expect(active().getByLabel("Queue agent", { exact: true })).toBeDisabled()
  await expect(active().locator(".direct-session-actions .direct-active-agent")).toContainText("build")
  await expect(active().locator(".direct-session-actions .context-pct")).toContainText("ctx 1k")
  await expect(active().locator(".direct-controls .context-pct, .direct-controls .direct-active-agent")).toHaveCount(0)
  expect(
    await active()
      .locator(".direct-setting")
      .evaluateAll((labels) =>
        labels.map((label) =>
          [...label.childNodes]
            .filter((node) => node.nodeType === Node.TEXT_NODE)
            .map((node) => node.textContent)
            .join("")
            .trim(),
        ),
      ),
  ).toEqual(["", ""])
  await expect(editor()).toBeFocused()
  await page.keyboard.type("current visible message")
  await editor().evaluate((el) => el.setSelectionRange(2, 7))
  await editor().dispatchEvent("keydown", { code: "KeyM", key: "m", altKey: true })
  await expect(button("Steer")).toHaveAttribute("data-keyboard-target", "true")
  await editor().press("Meta+m")
  await expect(button("Queue")).toHaveAttribute("data-keyboard-target", "true")
  await expect(button("Queue").locator("kbd")).toHaveText("⌘/Ctrl↵")
  await expect(button("Aside").locator("kbd")).toHaveText("⌘M →")
  await editor().dispatchEvent("keydown", { code: "KeyM", key: "m", metaKey: true, repeat: true })
  await editor().dispatchEvent("keydown", { code: "KeyM", key: "m", metaKey: true, isComposing: true })
  await expect(button("Queue")).toHaveAttribute("data-keyboard-target", "true")
  await expect(active().getByLabel("Queue agent", { exact: true })).toBeEnabled()
  await expect(editor()).toHaveValue("current visible message")
  expect(await editor().evaluate((el) => [el.selectionStart, el.selectionEnd])).toEqual([2, 7])
  expect(inputs()).toHaveLength(0)
  fixture.holdAside = true
  await button("Aside").click()
  await expect(editor()).toBeFocused()
  await expect.poll(() => asides().length).toBe(1)
  expect(asides()[0].body.question).toBe("current visible message")
  await expect(button("Queue")).toHaveAttribute("data-keyboard-target", "true")
  await expect(button("Aside")).toBeDisabled()
  await editor().fill("newer visible text")
  await editor().press("Meta+m")
  fixture.holdAside = false
  fixture.asideReplies.shift()()
  await expect(page.locator(".aside-answer")).toContainText("ASIDE ONLY")
  await expect(editor()).toHaveValue("newer visible text")
  await expect(button("Aside")).toHaveAttribute("data-keyboard-target", "true")
  await page.getByRole("button", { name: "Close aside", exact: true }).click()

  await expect(active().getByLabel("Queue agent", { exact: true })).toBeDisabled()
  await editor().press("Meta+m")
  await expect(active().getByLabel("Queue agent", { exact: true })).toBeDisabled()
  await editor().press("Meta+m")
  await active().getByLabel("Queue agent", { exact: true }).selectOption("plan")
  fixture.loseInput = true
  await button("Queue").click()
  await expect(page.locator(".input-admission")).toContainText("Admission unknown")
  const unknown = inputs().at(-1).body
  expect(unknown).toMatchObject({ text: "newer visible text", delivery: "queue", agent: "plan" })
  await editor().fill("draft after unknown")
  await active().getByLabel("Queue agent", { exact: true }).selectOption("build")
  await active().getByLabel("Queue agent", { exact: true }).focus()
  await page.keyboard.press("Meta+m")
  await expect(editor()).toBeFocused()
  await page.reload({ waitUntil: "domcontentloaded" })
  await expect(editor()).toHaveValue("draft after unknown")
  await expect(button("Aside")).toHaveAttribute("data-keyboard-target", "true")
  await page.getByRole("button", { name: "Check and retry same input", exact: true }).click()
  await expect(page.locator(".input-admission")).toHaveCount(0)
  expect(inputs().at(-1).body).toEqual(unknown)
  await expect(editor()).toHaveValue("draft after unknown")
  await expect(page.locator(".input-receipts summary")).toContainText("1 queued, 0 steer")

  await button("Steer").click()
  await expect.poll(() => inputs().at(-1).body.delivery).toBe("steer")
  expect(inputs().at(-1).body.text).toBe("draft after unknown")
  expect(inputs().at(-1).body.agent).toBeUndefined()
  await expect(editor()).toHaveValue("")
  await expect(button("Steer")).toHaveAttribute("data-keyboard-target", "true")
  await expect(page.locator(".input-receipts summary")).toContainText("1 queued, 1 steer")
  await editor().fill("keyboard uses current target")
  await editor().press("Meta+m")
  await editor().press("Control+Enter")
  await expect.poll(() => inputs().at(-1).body.text).toBe("keyboard uses current target")
  expect(inputs().at(-1).body.delivery).toBe("queue")
  await expect(editor()).toHaveValue("")
  await expect(button("Steer")).toHaveAttribute("data-keyboard-target", "true")
  await page.screenshot({ path: "artifacts/direct-composer/desktop.png", fullPage: true })

  await editor().fill("idle starts in chat")
  await editor().press("Meta+m")
  await expect(button("Queue")).toHaveAttribute("data-keyboard-target", "true")
  fixture.setStatus("idle")
  await expect(page.locator(".topbar")).toContainText("idle")
  await expect(active().locator(".direct-submit-actions button")).toHaveCount(1)
  await expect(button("Send").locator("kbd")).toHaveText("⌘/Ctrl↵")
  await expect(button("Steer")).toHaveCount(0)
  await expect(button("Queue")).toHaveCount(0)
  await expect(button("Aside")).toHaveCount(0)
  await expect(active().getByLabel("Queue agent", { exact: true })).toBeDisabled()
  await editor().press("Meta+m")
  await expect(editor()).toHaveValue("idle starts in chat")
  const before = inputs().length
  fixture.holdNormal = true
  await button("Send").click()
  await expect(page.getByRole("region", { name: "Message status", exact: true })).toContainText("Sending")
  await expect.poll(() => normal().length).toBe(1)
  expect(inputs()).toHaveLength(before)
  await editor().press("Control+Enter")
  expect(normal()).toHaveLength(1)
  fixture.setStatus("busy")
  await expect(button("Queue")).toHaveAttribute("data-keyboard-target", "true")
  await editor().fill("new draft while chat sends")
  await editor().press("Meta+m")
  fixture.holdNormal = false
  fixture.normalReplies.shift()()
  await expect(page.getByRole("region", { name: "Message status", exact: true })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Dismiss send status", exact: true })).toHaveCount(0)
  await expect(active()).not.toContainText("A task message is being sent")
  await expect(editor()).toHaveValue("new draft while chat sends")
  await expect(button("Aside")).toHaveAttribute("data-keyboard-target", "true")
  expect(inputs()).toHaveLength(before)
  fixture.setStatus("idle")
  await expect(button("Send")).toBeVisible()
  await expect(active().getByRole("radio")).toHaveCount(0)
  await expect(active()).not.toContainText("Normal Send")
  await page.screenshot({ path: "artifacts/direct-composer/idle.png", fullPage: true })

  await button("Expand editor").click()
  await expect(page.locator(".relative-lines")).toBeVisible()
  await expect(editor()).toHaveValue("new draft while chat sends")
  await editor().press("Meta+m")
  await expect(active().locator(".direct-submit-actions button")).toHaveCount(1)
  await expect(button("Send")).toBeVisible()
  await expect(editor()).toHaveValue("new draft while chat sends")
  await editor().press("Escape")
  await editor().press("0")
  await editor().press("l")
  expect(await editor().evaluate((el) => el.selectionStart)).toBe(1)
  await editor().press("i")
  await page.screenshot({ path: "artifacts/direct-composer/expanded.png", fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(button("Send")).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "artifacts/direct-composer/mobile.png", fullPage: true })
  await page.evaluate(() => {
    document.documentElement.dir = "rtl"
  })
  await expect(button("Send")).toBeVisible()
  fixture.setStatus("busy")
  await expect(button("Aside")).toHaveAttribute("data-keyboard-target", "true")
  await expect(active().locator(".direct-submit-actions button")).toHaveCount(3)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "artifacts/direct-composer/rtl.png", fullPage: true })
  await page.getByRole("button", { name: /collapse/ }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.evaluate(() => {
    document.documentElement.dir = "ltr"
  })
  fixture.setStatus("idle")
  await expect(button("Send")).toBeVisible()

  await editor().evaluate((el) => {
    const data = new DataTransfer()
    data.items.add(new File([new Uint8Array([1, 2, 3])], "saved.png", { type: "image/png" }))
    el.dispatchEvent(new ClipboardEvent("paste", { clipboardData: data, bubbles: true }))
  })
  await expect(button("Remove saved.png")).toBeVisible()
  await expect(button("Queue")).toHaveCount(0)
  await expect(button("Aside")).toHaveCount(0)
  await expect(button("Send")).toBeEnabled()
  await editor().press("Meta+m")
  await expect(button("Remove saved.png")).toBeVisible()
  await button("Remove saved.png").click()
  const draftBefore = await editor().inputValue()
  page.once("dialog", (dialog) => dialog.dismiss())
  await button("Delete").click()
  await expect(editor()).toHaveValue(draftBefore)
  await expect(button("Nudge")).toBeVisible()
  await button("Nudge").click()
  await expect.poll(() => normal().length).toBe(2)
  expect(normal().at(-1).body.parts[0].text).toContain("Resume where you left off")
  await expect(editor()).toHaveValue(draftBefore)
  await expect(button("Nudge")).toBeEnabled()
  await editor().press("Control+Enter")
  await expect.poll(() => normal().length).toBe(3)
  expect(normal().at(-1).body.parts[0].text).toBe(draftBefore)
  expect(inputs()).toHaveLength(before)
  expect(asides()).toHaveLength(1)
  await expect(page.getByRole("region", { name: "Message status", exact: true })).toHaveCount(0)
  await editor().fill("uncertain normal message")
  fixture.loseNormal = true
  await button("Send").click()
  await expect(page.getByRole("region", { name: "Message status", exact: true })).toContainText("Outcome unknown")
  await expect(page.getByRole("button", { name: "Dismiss send status", exact: true })).toBeVisible()
  await expect(editor()).toHaveValue("uncertain normal message")
  await page.reload({ waitUntil: "domcontentloaded" })
  await expect(page.getByRole("region", { name: "Message status", exact: true })).toContainText("Outcome unknown")
  await expect(page.getByRole("button", { name: "Dismiss send status", exact: true })).toBeVisible()
  await expect(editor()).toHaveValue("uncertain normal message")
  expect(normal()).toHaveLength(4)
  expect(errors).toEqual([])
  expect(fixture.unexpected).toEqual([])
  console.log(
    "PASS direct B: visible payloads, per-message target, races/retry, idle chat/busy inputs, settings/images, Nudge, Markdown, expanded/Vim/mobile/RTL",
  )
} finally {
  await preview.close()
  await browser.close()
}
