import { createRequire } from "node:module"
import { startPanelPreview } from "./composer-panel-preview.mjs"
const { chromium, expect } = createRequire(new URL("../../app/package.json", import.meta.url))("@playwright/test")
const preview = await startPanelPreview()
preview.fixture.receipts = Array.from({ length: 25 }, (_, i) => ({ requestID: `pending-${i}`, sessionID: "ses_a", delivery: "queue", text: `Queued item ${i}`, agent: "build", admittedSeq: i + 1, timeCreated: 1, state: "pending" }))
const browser = await chromium.launch({ headless: true, channel: "chrome" })
const page = await browser.newPage()
await page.route("**/*", (route) => new URL(route.request().url()).origin === preview.origin ? route.continue() : route.abort())
try {
  await page.goto(preview.url, { waitUntil: "domcontentloaded" })
  await expect(page.locator(".input-receipts summary")).toContainText("25 queued")
  await page.locator(".composer-results").evaluate((el) => { el.scrollTop = el.scrollHeight })
  const box = await page.locator(".composer-results").boundingBox()
  const summary = page.locator(".input-receipts summary")
  const handle = await summary.boundingBox()
  expect(handle.y).toBeGreaterThanOrEqual(box.y)
  expect(handle.y + handle.height).toBeLessThanOrEqual(box.y + box.height)
  await summary.focus()
  await page.keyboard.press("Space")
  await expect(page.locator(".input-receipts")).not.toHaveAttribute("open")
  const pulse = page.locator(".session-work-spinner").first()
  await expect(pulse).toHaveCSS("animation-name", "session-work-pulse")
  await expect(pulse).toHaveCSS("transform", "none")
  expect(await pulse.evaluate((el) => el.getAnimations()[0].effect.getKeyframes().map((frame) => Number(frame.opacity)))).toEqual([0.45, 1, 0.45])
  await page.emulateMedia({ reducedMotion: "reduce" })
  await expect(pulse).toHaveCSS("animation-name", "none")
  await expect(pulse).toHaveCSS("opacity", "1")
  console.log("PASS sticky native summary, keyboard collapse, nonzero opacity pulse and reduced motion")
} finally { await preview.close(); await browser.close() }
